[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["common", "day??", "downloader", "template"]
resolver = "3"

[workspace.dependencies]
common = { path = "common" }
once_cell = "1.21.3"
rstest = "0.26.1"