[package]
name = "day07"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
bit-set = "0.8.0"
common.workspace = true
once_cell.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day07-benchmarks"
path = "benches/benchmarks.rs"
harness = false