[package]
name = "day02"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
once_cell.workspace = true


[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day02-benchmarks"
path = "benches/benchmarks.rs"
harness = false