[package]
name = "day09"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
common.workspace = true
once_cell.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day09-benchmarks"
path = "benches/benchmarks.rs"
harness = false